<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>
<style>
.icon-banners.type-4 .single-icon {
    padding-left: 55px;
}
.col-half-offset {
    margin-left: 4.166666667%;
}
</style>
<div class="container above_footer">

	<div class="icon-banners type-4 row middle-xl">
		
		<div class="single-icon col-xs-12 col-sm-6 col-md-2">
			<a href="<?php echo $base_url .'delivery-page'; ?>">
				<img src="<?php echo $base_url .'media/wysiwyg/footer/fast-del.png' ?>" alt="Fast delivery service">
				<span class="subtitle">Fast delivery service</span> 
			</a>
		</div>
		<div class="single-icon col-xs-12 col-sm-6 col-md-2 col-half-offset">
			<a href="<?php echo $base_url .'our-price-guarantee'; ?>">
				<img src="<?php echo $base_url .'media/wysiwyg/footer/debit.png' ?>" alt="Credit/Debit/Klarna">
				<span class="subtitle">Credit/Debit/Klarna</span> 
			</a>
		</div>
		<div class="single-icon col-xs-12 col-sm-6 col-md-2 col-half-offset">
			<a href="<?php echo $base_url .''; ?>">
				<img src="<?php echo $base_url .'media/wysiwyg/footer/1-year.png' ?>" alt="1 years warranty">
				<span class="subtitle">1 years warranty</span>
			</a>
		</div>
		<div class="single-icon col-xs-12 col-sm-6 col-md-2 col-half-offset">
			<a href="<?php echo $base_url .'our-price-guarantee'; ?>">
				<img src="<?php echo $base_url .'media/wysiwyg/footer/price-match.png' ?>" alt="Price match guarantee">
				<span class="subtitle">Price match guarantee</span> 
			</a>
		</div>
		<div class="single-icon col-xs-12 col-sm-6 col-md-2 col-half-offset">
			<a href="<?php echo $base_url .'our-price-guarantee'; ?>">
				<img src="<?php echo $base_url .'media/wysiwyg/footer/next-day.png' ?>" alt="Next Day Delivery">
				<span class="subtitle">Next Day Delivery </span><span class="line" style="font-size: 11px;color: rgba(0, 0, 0, 0.6);position: relative;top: 15px; width: 150px;">On selected items</span>
			</a>
		</div>
		
	
	</div>
</div>