<div id="view-page-bar" class="label">
    <div class="product_delivery_image">
    <img class="header-delevery-icon"height="40" width="150"src="<?php echo $this->getViewFileUrl(
                "images/free-del.png"
            ); ?>" alt="Free Delivery" />
    </div>
    <div class="product_expe_image">
    <img class="header-experience-icon" height="40" width="100" src="<?php echo $this->getViewFileUrl(
                "images/25-years-a.png"
            ); ?>" alt="25 years" />
    </div>
    <div class="header_rating_image">
        <span class="text">Customer Experience</span>
        <img width="115" height="24" src="<?php echo $this->getViewFileUrl(
            "images/Star_rating_4.5_of_5.png"
        ); ?>" alt="Customer Satisfaction" />
        <!-- <img width="115" height="24" src="/media/wysiwyg/customer-experience.jpg" alt="Customer Experience"> -->
    </div>
</div>