<style>
input, select {
	padding:5px;
}
div#page\:main-container th.cell-position {
    text-align: left;
    padding-bottom: 5px;
}
button#scalable_add {
    background-color: #eb5202;
    border-color: #eb5202;
    color: #ffffff;
    text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.25);
}
</style>
<div id="page:main-container" style="min-height:200px;">
			<table width="55%" cellspacing="0" class="data border" id="question_grid" style="padding: 0px 20px;">
			<thead>
				<tr class="headings">
					<th class="cell-position"><span>Date from</span></th>					
					<th class="cell-position"><span>Date To</span></th>
					<th class="cell-position"><span>Filtered by</span></th>
					<th class="cell-position"><span>Actions</span></th>
				</tr>
			</thead>   
			
			<tbody id="trgrid1">
			<tr> 
				<td class="cell-position"><input type="text" id="datepickerFrom"></td>				
				<td class="cell-position"><input type="text" id="datepickerTo"></td>
				<td class="cell-position">
					<select class="cell-position" type="text" id="filteredBy">
						<option value="">All</option>
						<option value="processing">Processing</option>
						<option value="complete">Complete</option>
						<option value="pending">Pending</option>
						<option value="cancelled">Cancelled</option>
						<option value="partial refund">Partial Refund</option>
					</select>
				</td>
				<td class="cell-position"><button class="scalable save" type="button" title="Edit" id="scalable_add">Export Orders</button>
				<div class="custom_spin" style="background: rgba(255, 255, 255, 0.5);bottom: 0;left: 0;position: absolute;right: 0;top: 0;z-index: 399;display:none;height:300px;">
					<div class="spinner" style="font-size: 4rem;left: 50%;margin-left: -2rem;margin-top: -2rem;position: absolute;top: 50%;">
						<span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
					</div>
				</div>
				</td>
			</tr>    
		</tbody>
	  </table>
	  <div id="messages" style="margin: 10px 20px;"><span></span></div>
</div>
<script>
require([
        'jquery',
		'jquery/ui'
    ], function ($) {
	jQuery(document).ready(function () {
		jQuery( "#datepickerFrom" ).datepicker();jQuery( "#datepickerTo" ).datepicker();
		jQuery('#scalable_add').click(function(){				
			var datepickerFrom = jQuery('#trgrid1 #datepickerFrom').val();
			var datepickerTo = jQuery('#trgrid1 #datepickerTo').val();
			var filteredBy = jQuery('#trgrid1 #filteredBy').val();
			var mydatepickerFrom = new Date(datepickerFrom);
			var mydatepickerTo = new Date(datepickerTo);
			var cur_date = new Date();

			if(datepickerFrom!='' && datepickerTo!='')
			{
				if(mydatepickerFrom > cur_date){
					alert('You cannot enter a from-date in the future!');
				}
				else if(mydatepickerTo > cur_date){
					alert('You cannot enter a to-date in the future!');
				}
				else{
					jQuery(".custom_spin").show();
					jQuery.ajax({
						type: "POST",
						url: "<?php echo $block->getUrl('importtracknumber/orderindex/ordersget', ['_secure' => true]); ?>",
						data: {dateFrom:datepickerFrom,dateTo:datepickerTo,filterBy:filteredBy},
						success: function(data) {
							if(data) 
							{
								location.reload();
							}	
							jQuery(".custom_spin").hide();
						}
					});
				}
			}
			else{
				alert("Please enter the ranges");
			}
		});
	});
});

</script>