<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
      $orderData = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
$ordervalue = $orderData->getGrandTotal();
$ordercurrency = $orderData->getOrderCurrencyCode();
$orderid = $orderData->getEntityId();
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>

<!-- Event snippet for Conversions / Sales conversion page -->
<script>
 gtag('event', 'conversion', {
   'send_to': 'AW-990484069/8YgECNWU-JQBEOWsptgD',
   'value': <?php echo $ordervalue; ?>,
   'currency': '<?php echo $ordercurrency; ?>',
   'transaction_id': '<?php echo $block->getOrderId(); ?>'
 });
</script>
<script type="text/javascript">
require([
        'jquery',
    ], function ($) {
        $(window).load(function(){
			console.log("testing theme");
			var curl = window.location.href;
			$.ajax({
			  url: curl,
			  cache: false,
			  success: function(){
				$("input#billing-address-same-as-shipping").trigger('click');
				console.log("sucess theme");
			  }
			});
			//jQuery("input#billing-address-same-as-shipping").trigger('click');
			//jQuery("#billing-address-same-as-shipping").prop( "checked", true );
        });
	});
</script>