<?php $related_collection = $block->getItems(); 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helperImport   = $objectManager->get('\Magento\Catalog\Helper\Image');
?>
<?php if(count($related_collection) > 0){ ?>
<?php if(count($related_collection) > 0 && count($related_collection) <=3){ ?>
	<div class="right-detail-relative">
		<p class="reco-product"><?php echo __("Related Products"); ?></p>
		<div class="row">
		
			<?php foreach($related_collection as $catpro){ 
			$proname = $catpro->getName();
			$prourl = $catpro->getProductUrl();
			$imageUrl = $helperImport->init($catpro,'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(220)->getUrl();
			//print_r($catpro->getData());
			?>
				<div class="col-md-3 col-sm-6 col-xs-6 bootCols">
					<a href="<?php echo $prourl; ?>" title="<?php echo $proname; ?>" class="product-image">
						<img class="rel_img" src="<?php echo $imageUrl; ?>" alt="<?php echo $proname; ?>" />
						<?php //echo $block->getImage($catpro, 'related_products_list')->toHtml(); ?>
					</a>
					<div class="list-product-detaikl reco-pro-price">
					    
						<p class="list-product-name"><?php echo $proname; ?></p>
						<?php
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); 
						$msrpprice =   $catpro->getResource()->getAttribute('msrp')->getFrontend()->getValue($catpro); 
						$formattedPrice = $priceHelper->currency($msrpprice, true, false); ?>
						<p class="list-product-price-old"> <?php echo "RRP: "; ?><s><span class="price">
								<?php echo $formattedPrice; ?>
						</span></s></p>
								<?php echo $block->getProductPrice($catpro); ?>
					</div>
					<button class="add-list-basket" onclick="window.location.href='<?= $prourl; ?>'"><span><span><?php echo "VIEW MORE"; ?></span></span></button>
				</div>

			<?php } ?>
			
		</div>
	</div>
<?php }else{ ?>
	<div class="right-detail">
		<p class="reco-product"><?php echo __("Related Products"); ?></p>
		<div class="row">
		<div class="swiper-container releted">
			<div class="swiper-wrapper">
			<?php foreach($related_collection as $catpro){ 
			$proname = $catpro->getName();
			$prourl = $catpro->getProductUrl();
			$imageUrl = $helperImport->init($catpro,'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(220)->getUrl();
			//print_r($catpro->getData());
			?>
				<div class="list-product detail-listproduct swiper-slide">
					<a href="<?php echo $prourl; ?>" title="<?php echo $proname; ?>" class="product-image">
						<img class="rel_img" src="<?php echo $imageUrl; ?>" alt="<?php echo $proname; ?>" />
						<?php //echo $block->getImage($catpro, 'related_products_list')->toHtml(); ?>
					</a>
					<div class="list-product-detaikl reco-pro-price">
					    
						<p class="list-product-name"><?php echo $proname; ?></p>
						<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); 
				$msrpprice =   $catpro->getResource()->getAttribute('msrp')->getFrontend()->getValue($catpro); 
				$formattedPrice = $priceHelper->currency($msrpprice, true, false); ?>
				<p class="list-product-price-old"> <?php echo "RRP: "; ?><s><span class="price">
						<?php echo $formattedPrice; ?>
				</span></s></p>
						<?php echo $block->getProductPrice($catpro); ?>
					</div>
					<button class="add-list-basket" onclick="window.location.href='<?= $prourl; ?>'"><span><span><?php echo "VIEW MORE"; ?></span></span></button>
				</div>

			<?php } ?>
			</div>
			<div class="swiper-button-prev rel"></div>
			<div class="swiper-button-next rel"></div>
		
		</div>
		</div>
	</div>
<?php } ?>

<?php if(count($related_collection) >= 4){ ?>
<script type="text/x-magento-init">
	{
		".releted": {
			"Meigee_Sirena/js/theme_carousel":{
				"loop":true,
				"navigation":true,
				"pagination":false,
				"autoplay":true
			}
		}
	}
</script>
<?php } ?>

<style>
.page-wrapper .swiper-container.releted .swiper-button-next.rel, .page-wrapper .swiper-container.releted .swiper-button-prev.rel{
	width:30px;
	opacity:1;
	background-color:rgba(0, 0, 0, 0.4);
	height:40px;top:25%;
}

.page-wrapper .swiper-container.releted .swiper-button-prev.rel{
	left:27px;
}

.page-wrapper .swiper-button-prev.rel:before,.page-wrapper .swiper-button-next.rel:before{
	position:relative;
	bottom:20px;
	color:#fff;
}

.sidebar .right-detail .reco-product{
	font-size:16px;
	color:#000;
}

.swiper-container.releted .swiper-slide img.rel_img{
	width:auto;
	margin:0 auto;
}
</style>
<?php } ?>

